# Generated by Django 3.2 on 2021-05-28 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_author', models.CharField(max_length=150, verbose_name='author')),
                ('message', models.CharField(max_length=10500, verbose_name='message')),
                ('text_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
