# Generated by Django 3.2 on 2021-05-27 05:49

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('body', ckeditor.fields.RichTextField(verbose_name='body')),
                ('bg_image', models.ImageField(upload_to='post_image/', verbose_name='bg-image')),
                ('author', models.CharField(blank=True, max_length=50, verbose_name='author')),
                ('auth_avatar', models.ImageField(blank=True, upload_to='post_image/auth_avatar', verbose_name='auth image')),
                ('post_slug', models.SlugField(unique=True, verbose_name='slug')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_posts')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
