# Generated by Django 3.2 on 2021-05-28 05:27

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='name')),
                ('c_slug', models.SlugField(verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('body', ckeditor.fields.RichTextField(verbose_name='body')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('post_slug', models.SlugField(unique=True, verbose_name='slug')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_posts')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='category')),
                ('user_pro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.userprofile', verbose_name='user_link')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-date'],
            },
        ),
    ]
