# Generated by Django 3.2 on 2021-05-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='c',
            field=models.CharField(blank=True, max_length=2, verbose_name='C,C++,C#'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='java',
            field=models.CharField(blank=True, max_length=2, verbose_name='Java'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='js',
            field=models.CharField(blank=True, max_length=2, verbose_name='JS'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='php',
            field=models.CharField(blank=True, max_length=2, verbose_name='PHP'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='python',
            field=models.CharField(blank=True, max_length=2, verbose_name='Python'),
        ),
    ]
